#image: gradle:latest

stages:
  - build
  - test
  - measure

before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - ls
#  - gradle wrapper

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build #assemble
  artifacts:
    paths:
      - build/libs/*.jar
      - build/distributions/*
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  before_script:
    - gradle wrapper
  script:
    - ./gradlew check

run_experiment:
  stage: measure
  when: manual
  only:
    - master
  artifacts:
    paths: 
      - result.zip
      - summary.txt
      - simpleRandom/*.ttl
      - complexRandom/*.ttl
      - ./*.log
  script:
    - gradle build
    - unzip build/distributions/*.zip
    - python data/genconfig.py -p data/simplePolicies -o configSimple.ttl -m data/userlocationpolicy.ttl -r data/cpss-special-integrated.ttl
    - python data/genconfig.py -p data/complexPolicies -o configComplex.ttl -m data/userlocationpolicy.ttl -r data/cpss-special-integrated.ttl
    - mashup-privacy-checker/bin/mashup-privacy-checker -check configSimple.ttl > configSimple.log
    - mashup-privacy-checker/bin/mashup-privacy-checker -check configComplex.ttl > configComplex.log
    - python scripts/genpolicy.py -d simpleRandom -n 100 
    - python scripts/genpolicy.py -d complexRandom -n 100 -intersection
    - python scripts/makesummary.py -i configSimple.log >> summary.txt
    - python scripts/makesummary.py -i configComplex.log >> summary.txt
    - zip result.zip configSimple.ttl configSimple.log configComplex.ttl configComplex.log summary.txt data/simplePolicies data/complexPolicies

after_script:
  - echo "End CI"
